project:
  type: website
  output-dir: _site

website:
  title: "EstBioInfo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: members.qmd
        text: Members
      - href: training.qmd
        text: Training
      - href: software.qmd
        text: Software
      # - href: activities.qmd
      #   text: Activities
      - href: contact.qmd
        text: Contact
        
  # sidebar:
  #   background: primary
  #   style: docked
  #   search: true
  #   contents:
  #     - href: index.qmd
  #       text: Home
  #     - href: about.qmd
  #       text: About
  #     - href: research.qmd
  #       text: Research
  #     - href: publications.qmd
  #       text: Publications
  #     - href: members.qmd
  #       text: Members
  #     - href: training.qmd
  #       text: Teaching
  #     - href: software.qmd
  #       text: Sofwtare
  #     - href: activities.qmd
  #       text: Activities
  #     - href: contact.qmd
  #       text: Contact


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    embed_resources: false




